### ISSUE TITLE
Settings stored in database 

### ISSUE THREAD

**Issue by KamilGrzechulski** [KamilGrzechulski/SoftCRM#31]
At this moment settings has been stored in files. Let's implement this to store in database.

**Comment by WesleyNobrega** [comment]
I found a error in new update. In the \App\Console\Commands\processSoftCRM.php, line 63:

$systemLogs->insertSystemLogs('First usage of process-softcrm command', 200);

This method requires 3 params, but only 2 were passed !

**Comment by KamilGrzechulski** [comment]
@WesleyNobrega #fixed.
