### ISSUE TITLE
Change password for administrator

### ISSUE THREAD

**Issue by KamilGrzechulski** [KamilGrzechulski/SoftCRM#32]

**Comment by WesleyNobrega** [comment]
After the last updates the system went down
![Captura de tela de 2020-01-13 22-34-57](https://user-images.githubusercontent.com/32504149/72306561-520ea400-3656-11ea-98fb-6cae94b4c6ed.png)
![Captura de tela de 2020-01-13 22-34-57](https://user-images.githubusercontent.com/32504149/72306562-5470fe00-3656-11ea-981e-427120698f39.png)

**Comment by KamilGrzechulski** [comment]
@WesleyNobrega Drop your database and run again php artisan process-softcrm

**Comment by WesleyNobrega** [comment]
I did what you suggested, clone the repository again and redo the settings including the bank. But nothing appears, I see that renders, but nothing appears.
I use docker containers through laradock, I don't know if you know it. Until that I redid the images the containers, but still nothing appears, neither in the dashboard nor in the other views.
![Captura de tela em 2020-01-14 17-47-02](https://user-images.githubusercontent.com/32504149/72381270-e67c1380-36f5-11ea-9f05-a4cd14758f7b.png)

**Comment by KamilGrzechulski** [comment]
@WesleyNobrega #fixed.

**Comment by WesleyNobrega** [comment]
What was the problem ?

**Comment by KamilGrzechulski** [comment]
@WesleyNobrega lovely CSS problems. :)
