### ISSUE TITLE
Got ErrorException after installation and login

### ISSUE THREAD

**Issue by datvoquoc** [KamilGrzechulski/SoftCRM#34]
Hi, 
After installation, I tried to login by admin account.

But it threw Error Exception like as below
**ErrorException
Undefined property: stdClass::$Tables_in_softcrm**
![image](https://user-images.githubusercontent.com/88045856/146505052-b5e39b63-12de-4e2c-ae39-3caa02e0663a.png)

Can you give me any hint for resolve it ?

Regards

**Comment by KamilGrzechulski** [comment]
Hello @datvoquoc 

You got this error because you have another name of database than 'softcrm'. I have marked this issue as "Need to be fixed".

**Actually, I have fixed this issue, and you can pull changes from master branch.**

Thank you for support.

**Comment by datvoquoc** [comment]
Hi @KamilGrzechulski 
Thanks for your fast responding. 

I tried and it has been fixed.

Regards.

**Comment by sreeni0076** [comment]
Tried connecting this application to a Mysql db getting error like 

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'sales.sqlite_master' doesn't exist (Connection: mysql, SQL: SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%')

and error is pointing to \vendor\laravel\framework\src\Illuminate\Database\Connection.php :825

![Image](https://github.com/user-attachments/assets/0d107d12-c7ff-4d09-b4ed-dd8b1e9c3059)

kindly help
