### ISSUE TITLE
Notification message is not correct

### ISSUE THREAD

**Issue by datvoquoc** [KamilGrzechulski/SoftCRM#35]
Hi,
At the **List of clients** page, I tried to update `Status` to `Inactive`. 
But the notification message is showing **Client has been active**

I think it is not approciate. 
![image](https://user-images.githubusercontent.com/88045856/146507938-f042e2f8-9ea0-4120-96fc-8e55d428d4f3.png)

**Comment by KamilGrzechulski** [comment]
Hello @datvoquoc 

Actually, I have fixed this issue, and you can pull changes from master branch.

Thanks for your support.

**Comment by datvoquoc** [comment]
Thanks for your fast response.
